name: Build and Deploy
on:
  #push:
  #  branches: [main]
  #  # Publish semver tags as releases.
  #  tags: ["v*.*.*"]
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
  APP_NAME: ${{ vars.APP_NAME }}
  JOB_IMAGE_NAME: ${{ vars.JOB_IMAGE_NAME }}
  JOB_CRON_EXPRESSION: ${{ vars.JOB_CRON_EXPRESSION }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: azure
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure required Azure resouces
        run: ${{ github.workspace }}/scripts/action-pre-build.sh -r ${{ vars.RESOURCE_GROUP }} -c ${{ vars.CONTAINER_REGISTRY_NAME }}

      - name: Collect Client credentials for Container Registry
        run: |
          REGISTRY_USERNAME=$(echo $AZURE_CREDENTIALS | jq -r '.["clientId"]')
          REGISTRY_PASSWORD=$(echo $AZURE_CREDENTIALS | jq -r '.["clientSecret"]')
          echo "::add-mask::$REGISTRY_USERNAME"
          echo "::add-mask::$REGISTRY_PASSWORD"
          echo REGISTRY_USERNAME=$REGISTRY_USERNAME >> $GITHUB_ENV
          echo REGISTRY_PASSWORD=$REGISTRY_PASSWORD >> $GITHUB_ENV

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src/app
          acrName: ${{ vars.CONTAINER_REGISTRY_NAME }}
          acrUsername: ${{ env.REGISTRY_USERNAME }}
          acrPassword: ${{ env.REGISTRY_PASSWORD }}
          containerAppName: ${{ vars.APP_NAME }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
          location: ${{ vars.LOCATION }}
          targetPort: ${{ vars.APP_TARGET_PORT }}
  
      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.JOB_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha
      
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/job
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and deploy Container App Job
        run: ${{ github.workspace }}/scripts/create-job.sh -i ${{ vars.JOB_IMAGE_NAME }}
